remote_theme: mmistakes/minimal-mistakes@4.9.0
title: "Leanne Fortney"
email: leannefortneyartist@gmail.com
description: "Artist & Innovation Facilitator, Leanne Fortney, supports individuals and teams in overcoming stuck thinking, activating new perspectives, and turning ideas into meaningful, real-world solutions."
url: "https://leannefortney.com"

minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate

author:
  name: "Leanne Fortney"
  avatar: "/images/duoface.png"
  bio: "Artist & Innovation Facilitator supporting individuals and teams in transforming challenges into fresh ideas and real-world solutions."
  instagram: "leannefortney_art"
  facebook: "ArtistLeanneFortney"
  links:
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://www.tiktok.com/@leannefortney"
      title: "TikTok"
